MVCAPP/Controllers/MarketDownstairsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;

namespace MVCAPP.Controllers
{
    public class MarketDownstairsController : Controller
    {
        // GET: MarketDownstairs
         //分页返回所有商品，每页六个
         int pageSize = 6;
        public ActionResult MarketIndex(int page = 1)
        {

            ViewModel.GoodsListModel goodsList = new ViewModel.GoodsListModel
            {
                goodsList = new ClassLibrary.MarketDownstairs().getAllGoods(page, pageSize),
                pageInfo = new ViewModel.PagingInfo { currentpage = page, itemperpage = pageSize, Totalitems = new ClassLibrary.MarketDownstairs().getTotalCount() }
            };
            return View(goodsList);

        }
        /// <summary>
        /// 我的商店
        /// </summary>
        /// <returns>返回商店信息</returns>
        [Authorize(Roles = "普通用户")]
        public ActionResult MyMall()
        {
            string owner = User.Identity.Name;
            ViewModel.MyMallInfo myMallInfo = new ClassLibrary.MarketDownstairs().GetMyMallInfo(owner);
            return View(myMallInfo);
        }

        [HttpPost]
        public ActionResult MyMall(ViewModel.MyMallInfo myMallInfo)
        {
            myMallInfo.Owner = User.Identity.Name;
            if (new ClassLibrary.MarketDownstairs().UpdateMyMallInfo(myMallInfo))
            {
                ViewModel.MyMallInfo myNewMallInfo = new ClassLibrary.MarketDownstairs().GetMyMallInfo(myMallInfo.Owner);
                return View(myNewMallInfo);
            }
            return View(myMallInfo);
        }
        /// <summary>
        /// 获取具体的商品信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult GetDetail(int id)
        {
            ViewModel.GoodDetailModel goodDetail = new ViewModel.GoodDetailModel
            {
                MallGood = new ClassLibrary.MarketDownstairs().GetGoodDetail(id),
                MallInfo = new ClassLibrary.MarketDownstairs().GetGoodMall(id)
            };
            return View(goodDetail);


        }
        /// <summary>
        /// 用户上传商品
        /// </summary>
        /// <returns></returns>
        public ActionResult UploadGood()
        {
            ViewModel.UpLoadGoodModel model = new ViewModel.UpLoadGoodModel();
            model.shopId = new ClassLibrary.MarketDownstairs().GetNowMallID(User.Identity.Name);

            return View(model);

        }

        [HttpPost]
        public ActionResult UploadGood(ViewModel.UpLoadGoodModel uploadModel, HttpPostedFileBase image)
        {
            //if (image != null)
            //{
            //    string upLoadPath = Server.MapPath("~/Content/Images/");

            //    Random rn = new Random();
            //    string unique = rn.Next(1000).ToString();

            //    string fileName = uploadModel.GoodName + unique + System.IO.Path.GetExtension(image.FileName);
            //    ///获取存储物理路径

            //    string fileAdress = upLoadPath + fileName;

            //    string photoAdress = "/content/Images/" + fileName;
            //    image.SaveAs(fileAdress);
               ///获取提交上来的图片路径
              string photoAddress = Request.Form["imageAddress"];
              if (photoAddress != null)
              {
                  bool flag = new ClassLibrary.MarketDownstairs().UpLoadGoodInfo(uploadModel, photoAddress);
                  if (flag)
                  {

                      return RedirectToAction("MarketIndex");

                  }
                  else
                  {
                      return View(uploadModel);
                  }
              }
              else
              {

                  return View(uploadModel);
 
              }

            //}
            //else
            //{
            //    return View(uploadModel);
            //}



        }

        /// <summary>
        /// 根据关键词获得指定的货物
        /// </summary>
        /// <returns></returns>
        public ActionResult GetRightGoods(int page = 1)
        {

            string keyWords = Server.HtmlDecode(this.Request.Form["keyWords"]);
            if (keyWords != null)
            {
                
               
                Session["key"] = keyWords;
                return View(new ClassLibrary.MarketDownstairs().getRightGoods(keyWords,page,pageSize));

            }
            else
            {
                if (Session["key"] != null)
                {
                   
                    return View(new ClassLibrary.MarketDownstairs().getRightGoods(keyWords, page, pageSize));

                }
                return RedirectToAction("MarketIndex");
            }

        }

        /// <summary>
        /// 获取自己商店的货物
        /// </summary>
        /// <returns></returns>
        public ActionResult GetMyMallGoods()
        {
            string userNow = User.Identity.Name;

            return View(new ClassLibrary.MarketDownstairs().getMyMallGoods(userNow));


        }

        /// <summary>
        /// 根据货物Id删去指定货物
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult DeleteGood(int id)
        {
            if (new ClassLibrary.MarketDownstairs().DeleteGoods(id))
            {
                return RedirectToAction("MyMall");

            }
            else

            {
                ///之后设置错误页面
                return View();
            }
           
        }
        /// <summary>
        /// 显示系统通知
        /// </summary>
        /// <returns></returns>
        public ActionResult Notice()
        {

            return View();
 
        }
       

    }
}

MVCAPP/Views/MarketDownstairs/GetRightGoods.cshtml
@{
    ViewBag.Title = "GetRightGoods";
}
@model ViewModel.GoodsListModel
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Tomato</a>
        </div>
        <!--[logo]>
        <a class="navbar-brand" href="#">
        </a> <!-->
        <ul class="nav navbar-nav " role="tablist">
            <li><a href="/Home/Index">首页</a></li>
            <li><a href="/PartyActivities/PartyIndex">社团互动</a></li>
            <li class="active"><a href="/MarketDownstairs/MarketIndex">楼下小铺</a></li>
            <li><a href="#">新生指南</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            @if (User.IsInRole("普通用户"))
            {
                // [@Html.ActionLink("个人中心", "PersonalInfo", "Account")]
                //[ @Html.ActionLink("注销", "LogOff", "Account") ]
                <li style="color:white">
                    <a>欢迎<small>@User.Identity.Name !</small></a>
                </li>
                <li><a href="/MarketDownstairs/MyMall">我的商店</a></li>
                <li><a href="/Account/LogOff">注销</a></li>

            }
            @if (!User.IsInRole("普通用户"))
            {

                <li><a href="/Account/Reviselogin">登陆/注册</a></li>

            }
        </ul>
       

    </div>
</nav>

@if (Model.goodsList.Count == 0)
{

    <h2>您所搜索的商品暂不存在</h2>

}
else
{
    <div class="container" style="background-color:#fff;">
        <div style="display:block;position:relative; top:60px;">
            <div class=" row row-offcanvas row-offcanvas-right">

                <div class="col-xs-12 col-sm-9">
                    <div class="jumbotron">
                        <h1>搜索结果！</h1>
                        @using (Html.BeginForm("GetRightGoods", "MarketDownstairs"))
                        {
                            <div class="col-lg-6">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="搜索" name="keyWords">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="submit">Go!</button>
                                    </span>
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        }
                    </div>
                    <div class="row">

                        @foreach (var i in Model.goodsList)
                        {

                            <div class="col-sm-6 col-md-4" style="border:1px;">
                                <div class="thumbnail">
                                    <img data-src="holder.js/100%x150" alt="100%x200" src="@i.GoodPhoto" style="height: 150px; width: 100%; display: block;">
                                    <h2>@i.GoodName</h2>
                                    <p>简介： @i.GoodIntroduction</p>
                                    <p>数量： @i.GoodNumber</p>
                                    <p>价格（元）： @i.GoodPrice</p>
                                    <hr style="border:none;" />
                                    <p>
                                        <a class="btn btn-primary" href="/MarketDownstairs/GetDetail?id=@i.GoodID" role="button">View details</a>
                                    </p>
                                </div>
                            </div>
                        }

                    </div><!--/row-->
                </div><!--/span-->

            </div><!--/row-->

            <ul class="pagination">
                <li><a href="#">&laquo;</a></li>
                @for (int i = 1; i <= @Model.pageInfo.totalpages; i++)
                {

                    <li><a href="/MarketDownstairs/MarketIndex?page=@i">@i </a></li>

                }

                <li><a href="#">&raquo;</a></li>

            </ul>

            <hr>
        </div>

    </div><!--/.container-->



}

MVCAPP/Views/MarketDownstairs/MarketIndex.cshtml
@{
    ViewBag.Title = "楼下小铺";

}

@model ViewModel.GoodsListModel
@using Common



<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Tomato</a>
        </div>
        <!--[logo]>
        <a class="navbar-brand" href="#">
        </a> <!-->
        <ul class="nav navbar-nav " role="tablist">
            <li><a href="/Home/Index">首页</a></li>
            <li><a href="/PartyActivities/PartyIndex">社团互动</a></li>
            <li class="active"><a href="/MarketDownstairs/MarketIndex">楼下小铺</a></li>
            <li><a href="#">新生指南</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            @if (User.IsInRole("普通用户"))
            {
                // [@Html.ActionLink("个人中心", "PersonalInfo", "Account")]
                //[ @Html.ActionLink("注销", "LogOff", "Account") ]
                <li style="color:white">
                    <a>欢迎<small>@User.Identity.Name !</small></a>
                </li>
                <li><a href="/MarketDownstairs/MyMall">我的商店</a></li>
                <li><a href="/Account/LogOff">注销</a></li>

            }
            @if (!User.IsInRole("普通用户"))
            {

                <li><a href="/Account/Reviselogin">登陆/注册</a></li>

            }
        </ul>



    </div>
</nav>

<div class="container" style="background-color:#fff;height:auto; width:100%">
   
    <div style="display:block;position:relative;top:60px;">
        <div class="row row-offcanvas row-offcanvas-right" >

            <div class="col-xs-12 col-sm-9">
                <p class="pull-right visible-xs">
                    <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
                </p>
                <div class="jumbotron">
                    <h1>楼下小铺！</h1>
                    @using (Html.BeginForm("GetRightGoods", "MarketDownstairs"))
                    {
                        @*<label>Tags:</label>
                            <input id="tags" class="ui-autocomplete-input" placeholder="搜索" name="keyWords" />
                            <button type="submit" class="btn btn-sm btn-default">搜索</button>*@

                        <div class="col-lg-6">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="搜索" name="keyWords">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">Go!</button>
                                </span>
                            </div><!-- /input-group -->
                        </div><!-- /.col-lg-6 -->


                    }
                </div>
                <div class="row">
                    @foreach (var i in Model.goodsList)
                    {
                        <div class="col-sm-6 col-md-4" style="border:1px;">
                            <div class="thumbnail">
                                <div>
                                    <img data-src="holder.js/100%x150" alt="100%x200" src="@i.GoodPhoto" style="height: 150px; width: 100%; display: block;position:relative;" onmouseover="showfavortag()" onmouseout="    hidefavortag()">
                                </div>
                                
                                <div id="favorphoto"   style="height:150px;width:297px;background-color:lightblue;opacity: 0.4;filter:alpha(opacity=50);display:none;position:absolute;top:0px;">
                                    

                                </div>
                                <h2>@i.GoodName</h2>
                                <p>简介： @i.GoodIntroduction</p>
                                <p>数量： @i.GoodNumber</p>
                                <p>价格（元）： @i.GoodPrice</p>
                                <hr style="border:none;" />
                                <p>
                                    <a class="btn btn-primary" href="/MarketDownstairs/GetDetail?id=@i.GoodID" role="button">View details</a>
                                </p>
                            </div>
                        </div>
                    }

                </div><!--/row-->
            </div><!--/span-->



        </div><!--/row-->
        <div>
            <ul class="pagination">
                <li><a href="#">&laquo;</a></li>
                @for (int i = 1; i <= @Model.pageInfo.totalpages; i++)
            {

                    <li><a href="/MarketDownstairs/MarketIndex?page=@i">@i </a></li>

            }

                <li><a href="#">&raquo;</a></li>

            </ul>
        </div>
    </div> 

  

</div><!--/.container-->

<script type="text/javascript">
    
    function showfavortag() {

        document.getElementById("favorphoto").style.display = "block";

    }
    function hidefavortag() {

        document.getElementById("favorphoto").style.display = "none";

    }

</script>

MVCAPP/Views/MarketDownstairs/MyMall.cshtml
@{
    ViewBag.Title = "我的商店";
}
@model ViewModel.MyMallInfo

<link rel="stylesheet" href="../../Content/button/css/font-awesome.min.css">
<link rel="stylesheet" href="../../Content/button/css/buttons.css">
<script src="~/Content/JscrollPane/script/jquery.jscrollpane.min.js"></script>
<script src="~/Content/JscrollPane/script/jquery.mousewheel.js"></script>
<link href="~/Content/JscrollPane/style/jquery.jscrollpane.css" rel="stylesheet" />

<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Tomato</a>
        </div>
        <!--[logo]>
        <a class="navbar-brand" href="#">
        </a> <!-->
        <ul class="nav navbar-nav " role="tablist">
            <li><a href="/Home/Index">首页</a></li>
            <li><a href="/PartyActivities/PartyIndex">社团互动</a></li>
            <li><a href="/MarketDownstairs/MarketIndex">楼下小铺</a></li>
            <li><a href="#">新生指南</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            @if (User.IsInRole("普通用户"))
            {
                // [@Html.ActionLink("个人中心", "PersonalInfo", "Account")]
                //[ @Html.ActionLink("注销", "LogOff", "Account") ]
                <li style="color:white">
                    <a>欢迎<small>@User.Identity.Name !</small></a>
                </li>
                <li class="active"><a href="/MarketDownstairs/MyMall">我的商店</a></li>
                <li><a href="/Account/LogOff">注销</a></li>

            }
            @if (!User.IsInRole("普通用户"))
            {

                <li><a href="/Account/Reviselogin">登陆/注册</a></li>

            }
        </ul>



    </div>
</nav>


<div class="container">
    <div style="background-color:#fff;display:block;position:relative; top:60px;">
        &nbsp;&nbsp;&nbsp;
        <img src="~/Content/Images/MarketDefault.jpg" style="width:150px;height:150px;" class="img-circle" />
        <div id="mall-info" style="display:block; position:absolute;left:200px;top:10px;">
            <fieldset>
                @Html.HiddenFor(m => m.MallId)
                @Html.HiddenFor(m => m.Owner)

                <div class="editor-label">
                    <label>店名：</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.DisplayFor(m => m.MallName)
                </div>



                <div class="editor-label">
                    <label>电话：</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.DisplayFor(m => m.PhoneNumber)
                </div>



                <div class="editor-label">
                    <label>QQ:</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.DisplayFor(m => m.QQ)

                </div>



                <div class="editor-label">
                    <label>微信：</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.DisplayFor(m => m.WeChat)
                </div>
                <div class="editor-label">
                    <button onclick="changeUserData()" class="btn btn-primary">更改信息</button>
                </div>
            </fieldset>

        </div>

        @using (Html.BeginForm("MyMall", "MarketDownstairs", FormMethod.Post))
        {
            @Html.HiddenFor(m => m.MallId)
            @Html.HiddenFor(m => m.Owner)
            <div id="mall-infoform" style="display:none; position:absolute;left:200px;top:10px;">
                <fieldset>


                    <div class="editor-label">
                        <label>店名：</label>
                        &nbsp;&nbsp;&nbsp;
                        @Html.EditorFor(m => m.MallName)
                    </div>


                    <div class="editor-label">
                        <label>电话：</label>
                        &nbsp;&nbsp;&nbsp;
                        @Html.EditorFor(m => m.PhoneNumber)
                    </div>



                    <div class="editor-label">

                        <label>QQ:</label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        @Html.EditorFor(m => m.QQ)

                    </div>


                    <div class="editor-label">
                        <label>微信：</label>
                        &nbsp;&nbsp;&nbsp;
                        @Html.EditorFor(m => m.WeChat)
                    </div>
                    <div class="editor-label">
                        <button type="submit" class="btn btn-primary">完成修改</button>
                    </div>
                </fieldset>
            </div>

        }

        <div style="display:block;position:absolute;right:20px;top:10px;">

            <a class="button button-circle button-primary" onclick="window.location = '/MarketDownstairs/UploadGood'" role="button">上传货物</a>

        </div>

        @*导航菜单*@
        <ul class="nav nav-tabs" contenteditable="true" style="background-color:#eee7e7">
            <li id="mygoodli" class="active"><a onclick="showgoods()" role="button">我的货物</a></li>

            <li id="mynoticeli"><a onclick="showmessage()" role="button">通知</a></li>


        </ul>


        @*显示我的货物*@

        <div id="goods" aria-multiline="True" style="overflow:scroll;height:500px;">
            @Html.Action("GetMyMallGoods")
        </div>

        @*显示消息*@
        <div id="notice" style="display:none;">
            @Html.Partial("Notice")
        </div>

    </div>


</div>

<script type="text/javascript">
    function changeUserData() {
        document.getElementById("mall-info").style.display = "none";
        document.getElementById("mall-infoform").style.display = "block";
    }
    function showmessage() {
        document.getElementById("goods").style.display = "none";
        document.getElementById("notice").style.display = "block";
        document.getElementById("mygoodli").className = "";
        document.getElementById("mynoticeli").className = "active"
    }
    function showgoods() {
        document.getElementById("notice").style.display = "none";
        document.getElementById("goods").style.display = "block";
        document.getElementById("mynoticeli").className = "";
        document.getElementById("mygoodli").className = "active";

    }

</script>

MVCAPP/Views/MarketDownstairs/Notice.cshtml
@{
    Layout = null;
}
<div style="background-color:#fff">
    <h2>
        暂未有任何信息。
    </h2>
</div>

MVCAPP/Views/MarketDownstairs/UploadGood.cshtml
@{
    Layout = null;
}


@model ViewModel.UpLoadGoodModel

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!--为移动设备进行优化-->
    <title>UploadGood</title>
    <!-- Bootstrap -->
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="../../Content/css/unsliderstyle.css">

    @*扁平化样式*@
    @*<link href="~/Content/css/flat-ui.css" rel="stylesheet" />*@
    <style type="text/css">
        .banner {
            position: relative;
            overflow: auto;
        }

            .banner li {
                list-style: none;
            }

            .banner ul li {
                float: left;
            }
    </style>    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="~/Content/js/jquery.js"></script>
    <script src="~/Content/js/ajaxfileupload.js"></script>
    <script src="~/Content/js/uploadImage.js"></script>
</head>

<body>

    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Tomato</a>
            </div>
            <!--[logo]>
            <a class="navbar-brand" href="#">
            </a> <!-->
            <ul class="nav navbar-nav " role="tablist">
                <li><a href="/Home/Index">首页</a></li>
                <li><a href="/PartyActivities/PartyIndex">社团互动</a></li>
                <li class="active"><a href="/MarketDownstairs/MarketIndex">楼下小铺</a></li>
                <li><a href="#">新生指南</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                @if (User.IsInRole("普通用户"))
                {
                    // [@Html.ActionLink("个人中心", "PersonalInfo", "Account")]
                    //[ @Html.ActionLink("注销", "LogOff", "Account") ]
                    <li style="color:white">
                        <a>欢迎<small>@User.Identity.Name !</small></a>
                    </li>
                    <li><a href="/MarketDownstairs/MyMall">我的商店</a></li>
                    <li><a href="/Account/LogOff">注销</a></li>

                }
                @if (!User.IsInRole("普通用户"))
                {

                    <li><a href="/Account/Reviselogin">登陆/注册</a></li>

                }
            </ul>



        </div>
    </nav>

    <div class="container" style="background-color:#fff">
        <div style="height:600px;display:block; position:relative; top:60px; ">


            <div style="display:block;position:relative;left:20px;top:20px;">
                @using (Html.BeginForm("UploadGood", "MarketDownstairs", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.HiddenFor(m => m.shopId)
                    <div class="editor-field">
                        <label>商品名称：</label>
                        @Html.TextBoxFor(model => model.GoodName, new { @class = "form-control", placeholder = "商品名", style = "width:500px;height:50px" })
                    </div>


                    <div class="editor-field">
                        <label>商品数量：</label>
                        @Html.TextBoxFor(model => model.GoodNumber, new { @class = "form-control", placeholder = "商品数量", style = "width:500px;height:50px" })
                    </div>

                    <div class="editor-field">
                        <label>商品价格(元)：</label>
                        @Html.TextBoxFor(model => model.GoodPrice, new { @class = "form-control", placeholder = "商品价格", style = "width:500px;height:50px" })
                    </div>
                    <div class="editor-label">
                        <label>商品简介：</label>
                    </div>
                    <div class="editor-field">
                        @Html.TextAreaFor(model => model.Introduction, new { placeholder = "商品简介", style = "width:500px;height:100px" })
                    </div>
                    //异步上传图片后作为传递图片地址的媒介
                    <input type="text" id="imageAddress" name="imageAddress" value="" style="visibility:hidden">

                    <div class="editor-field">
                        <button class="btn btn-lg btn-primary">确定</button>
                    </div>
                }

                <div>
                    <label>
                        上传照片：
                    </label>
                    <div class="file-box">
                        <input type='text' name='textfield' id='textfield' class='txt' />
                        <input type='button' class='btn' value='浏览...' />
                        <input type="file" name="image" class="file" id="image" size="28" onchange="document.getElementById('textfield').value=this.value,uploadimage()" />
                        @*<input type="submit" name="submit" class="btn" value="上传" />*@


                    </div>
                    <div id="showimage" style="display:none">
                        <img id="imagebox" src="" style="width:200px;height:200px;" />
                    </div>


                </div>


            </div>




        </div>

    </div>
</body>
</html>


@*<script src="http://cdn.bootcss.com/jquery/1.9.1/jquery.min.js"></script>*@

<script src="~/Content/js/unslider.js"></script>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="http://cdn.bootcss.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="~/Content/js/bootstrap.min.js"></script>

<script>
                    if (window.chrome) {
                        $('.banner li').css('background-size', '100% 100%');
                    }

                    $('.banner').unslider({
                        speed: 500,
                        delay: 3000,
                        arrows: true,
                        fluid: true,
                        dots: true
                    });

                    //  Find any element starting with a # in the URL
                    //  And listen to any click events it fires
                    $('a[href^="#"]').click(function () {
                        //  Find the target element
                        var target = $($(this).attr('href'));

                        //  And get its position
                        var pos = target.offset(); // fallback to scrolling to top || {left: 0, top: 0};

                        //  jQuery will return false if there's no element
                        //  and your code will throw errors if it tries to do .offset().left;
                        if (pos) {
                            //  Scroll the page
                            $('html, body').animate({
                                scrollTop: pos.top,
                                scrollLeft: pos.left
                            }, 1000);
                        }

                        //  Don't let them visit the url, we'll scroll you there
                        return false;
                    });


</script>

<style type="text/css">
    .file-box {
        position: relative;
        width: 340px;
    }

    .txt {
        height: 30px;
        border: 1px solid #cdcdcd;
        width: 180px;
    }



    .file {
        position: absolute;
        top: 0;
        right: 80px;
        height: 24px;
        filter: alpha(opacity:0);
        opacity: 0;
        width: 260px;
    }
</style>