MVCAPP/Controllers/PartyActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel;
using ClassLibrary;

namespace MVCAPP.Controllers
{
    public class PartyActivitiesController : Controller
    {
        // GET: PartyActivities

        int pageSize = 6;
        /// <summary>
        /// 社团开始默认页面
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult PartyIndex(int page = 1)
        {
            return View(new PartyActivities().GetAllPartyInfo(pageSize, page));

        }
        /// <summary>
        /// 进入我的社团主页(这个作为了一个子动作在三个页面中都有它)
        /// </summary>
        /// <param name="partyName"></param>
        /// <returns></returns>
        /// 先注释掉权限测试完再开启
        [Authorize(Roles = "社团")]
        public ActionResult MyPartyInformation(string partyName)
        {
            partyName = Request["partyName"];
            if (partyName == null)
            {
                Response.Redirect("PartyIndex");
                return null;
            }
            PartyInformationModel partyInformationModel = new PartyInformationModel
            {

                partyInfo = new PartyActivities().GetPartyInfo(partyName),
                listPostInfo = new PartyActivities().GetPartyActivities(partyName)

            };

            return View(partyInformationModel);
        }
        /// <summary>
        /// 添加社团活动
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize(Roles = "社团")]

        public ActionResult AddActivities()
        {
            //to do 添加活动页
            PostInfo postInfo = new PostInfo();
            //postInfo.postPartyName = Request.Cookies[0].ToString();
            postInfo.postPartyName = User.Identity.Name;
            return View(postInfo);
        }

        [HttpPost]
        [Authorize(Roles = "社团")]
        public ActionResult AddActivities(PostInfo postInfo, HttpPostedFileBase image)
        {

            //to do 提交添加
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    postInfo.postPartyName = Request.Cookies[0].ToString();
                    string upLoadPath = Server.MapPath("~/Content/Images/PartyActivities");

                    Random rn = new Random();
                    string unique = rn.Next(1000).ToString();
                    string fileName = postInfo.postName + unique + System.IO.Path.GetExtension(image.FileName);
                    ///获取文件物理地址存入数据库
                    string fileAdress = upLoadPath + fileName;

                    string photoAdress = "/content/Images/PartyActivities/" + fileName;
                    image.SaveAs(fileAdress);
                    //将图片URL赋值模型的属性
                    postInfo.postPhotoURL = fileAdress;
                    if (new PartyActivities().AddActivities(postInfo))
                    {
                        Response.Write("活动添加成功！");
                        return RedirectToAction("MyPartyInformation");
                    }

                }


            }
            return View(postInfo);
        }
        /// <summary>
        /// 活动信息
        /// </summary>
        /// <param name="postName"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult PostInformation(string postName)
        {
            //to do 返回海报活动详情
            postName = Request["postName"];
            if (postName == null)
            {
                Response.Redirect("PartyIndex");
                return null;
            }
            PostInfo postInfo = new PostInfo();
            postInfo = new PartyActivities().GetPostInfo(postName);
            return View(postInfo);
        }

        [HttpGet]
        [Authorize(Roles = "社团")]
        public ActionResult SetPartyInfo(string partyName)
        {
            partyName = Request["partyName"];
            if (partyName == null)
            {
                Response.Redirect("PartyIndex");
                return null;
            }
            @ViewBag.partyName = partyName;
            ClassLibrary.PartyActivities setpartyinfo = new PartyActivities();
            return View(setpartyinfo.GetPartyInfo(partyName));

        }
        [HttpPost]
        public ActionResult SetPartyInfo(ViewModel.PartyInfo partyInfo, HttpPostedFileBase image)
        {
            if (image != null)
            {

                string upLoadPath = Server.MapPath("~/Content/Images/PartyLogo/");

                Random rn = new Random();
                string unique = rn.Next(1000).ToString();
                string fileName = partyInfo.partyName + unique + System.IO.Path.GetExtension(image.FileName);
                ///获取文件物理地址存入数据库
                string fileAdress = upLoadPath + fileName;

                string photoAdress = "/content/Images/PartyLogo/" + fileName;
                image.SaveAs(fileAdress);
                //将图片URL赋值模型的属性
                partyInfo.partyLogo = photoAdress;
                if (new PartyActivities().UpdataPartyInfo(partyInfo))
                {

                    return Content("<script type='text/javascript'>var truth=window.confirm('基本信息修改成功！！');if(truth){window.location='/PartyActivities/SetPartyInfo'}</script>");

                }

            }
            else
            {
                if (new ClassLibrary.PartyActivities().UpdataPartyInfo(partyInfo))
                {
                    return Content("<script type='text/javascript'>var truth=window.confirm('基本信息修改成功！！');if(truth){window.location='/PartyActivities/SetPartyInfo'}</script>");
                }

            }

            return View(partyInfo);

        }

        [HttpGet]
        [Authorize(Roles = "社团")]
        public ActionResult MyPartyActivities()
        {

            return View(new ClassLibrary.PartyActivities().GetPartyActivities(User.Identity.Name));

        }
        [HttpPost]
        public ActionResult MyPartyActivities(PostInfo postinfo)
        {
            //To Do
            return View();

        }

        [HttpGet]
        [Authorize(Roles = "社团")]
        public ActionResult Notice()
        {

            return View();

        }

        [HttpGet]
        [Authorize(Roles = "社团")]
        public ActionResult UpdatePassword()
        {

            return View();

        }

        [HttpPost]
        [Authorize(Roles = "社团")]
        public ActionResult UpdatePassword(partyUpdatePasswordModel model)
        {
            model.partyName = User.Identity.Name;
            if (ModelState.IsValid)
            {
                if (new PartyActivities().ReSetPartyPassword(model))
                {
                    Response.Write("密码修改成功！");
                }
                else
                {
                    Response.Write("原密码输入有误！");
                }
            }
            return View();
        }

        /// <summary>
        /// 点击viewDetails后进入的页面，属于普通用户或者游客可以进入的页面
        /// </summary>
        /// <returns></returns>
        public ActionResult ViewPartyDetails(string partyName)
        {

            PartyInformationModel partyInformationModel = new PartyInformationModel();
            partyInformationModel.partyInfo = new PartyActivities().GetPartyInfo(partyName);
            partyInformationModel.listPostInfo = new PartyActivities().GetPartyActivities(partyName);
            return View(partyInformationModel);

        }
    }
}

MVCAPP/Views/PartyActivities/AddActivities.cshtml
@{
    ViewBag.Title = "AddActivities";
}

@model ViewModel.PostInfo

<link href="~/Content/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
<link href="~/Content/css/bootstrap-datetimepicker.css" rel="stylesheet" />

<!--导航栏-->
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Tomato</a>
        </div>
        <!--[logo]>
        <a class="navbar-brand" href="#">
        </a> <!-->
        <ul class="nav navbar-nav " role="tablist">
            <li><a href="/Home/Index">首页</a></li>
            <li><a href="/PartyActivities/PartyIndex">社团互动</a></li>
            <li><a href="/MarketDownstairs/MarketIndex">楼下小铺</a></li>
            <li><a href="#">新生指南</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            @if (User.IsInRole("社团"))
            {
                // [@Html.ActionLink("个人中心", "PersonalInfo", "Account")]
                //[ @Html.ActionLink("注销", "LogOff", "Account") ]
                <li style="color:white">
                    <a>欢迎<small>@User.Identity.Name !</small></a>
                </li>
                <li class="active"><a href="/PartyActivities/SetPartyInfo?partyName=@User.Identity.Name">社团中心</a></li>
                <li><a href="/Account/LogOff">注销</a></li>



            }
            @if (!User.IsInRole("社团"))
            {

                <li><a href="/Account/PartyLoginIndex">登陆/注册</a></li>

            }
        </ul>
    </div>
</nav>

<div class="container" style="background-color:#fff;height:900px;">


    <div style="height:600px;display:block; position:relative; top:60px; ">
        @using (Html.BeginForm("AddActivities", "PartyActivities", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
        {

            @*@Html.HiddenFor(m => m.shopId)*@
            @Html.HiddenFor(m => m.postPartyName)

            <div style="display:block;position:relative;left:20px;top:20px;">
                <div class="editor-field">
                    <label>活动名称：</label>
                    @Html.TextBoxFor(model => model.postName, new { @class = "form-control", placeholder = "活动名称", style = "width:500px;height:50px" })
                </div>

                <div class="form-group">
                    <div>
                        <label>&nbsp;&nbsp;&nbsp;&nbsp;活动开始时间：</label>
                    </div>
                    <div class="input-group date form_date col-md-5" data-date="" data-date-format="yyyy-MM-dd" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
                        @Html.TextBoxFor(model => model.postBeginTime, new { @class = "form-control", placeholder = "活动开始时间", style = "width:500px;height:50px;" })
                        <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                    <input type="hidden" id="dtp_input2" value="" /><br />
                </div>

                <div class="form-group">
                    <div>
                        <label>&nbsp;&nbsp;&nbsp;&nbsp;活动结束时间：</label>
                    </div>
                    <div class="input-group date form_date col-md-5" data-date="" data-date-format="yyyy-MM-dd" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
                        @Html.TextBoxFor(model => model.postEndTime, new { @class = "form-control", placeholder = "活动结束时间", style = "width:500px;height:50px", @readonly = "True" })
                        <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                    <input type="hidden" id="dtp_input2" value="" /><br />
                </div>

                <div class="editor-label">
                    <label>网上票数：</label>
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.postEndTime, new { @class = "form-control", placeholder = "网上票数", style = "width:500px;height:50px" })
                </div>

                <div class="form-group">
                    <div>
                        <label>&nbsp;&nbsp;&nbsp;&nbsp;网上抢票开始时间：</label>
                    </div>
                    <div class="input-group date form_date col-md-5" data-date="" data-date-format="yyyy-MM-dd" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
                        @Html.TextBoxFor(model => model.postTicketBeginTime, new { @class = "form-control", placeholder = "网上抢票开始时间", style = "width:500px;height:50px", @readonly = "True" })
                        <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                    <input type="hidden" id="dtp_input2" value="" /><br />
                </div>

                <div class="form-group">
                    <div>
                        <label>&nbsp;&nbsp;&nbsp;&nbsp;网上抢票结束时间：</label>
                    </div>
                    <div class="input-group date form_date col-md-5" data-date="" data-date-format="yyyy-MM-dd" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
                        @Html.TextBoxFor(model => model.postTicketEndTime, new { @class = "form-control", placeholder = "网上抢票结束时间", style = "width:500px;height:50px", @readonly = "True" })
                        <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                    <input type="hidden" id="dtp_input2" value="" /><br />
                </div>

                <div>
                    <label>
                        上传照片：
                    </label>
                    <div class="file-box">
                        <input type='text' name='textfield' id='textfield' class='txt' />
                        <input type='button' class='btn' value='浏览...' />
                        <input type="file" name="image" class="file" id="fileField" size="28" onchange="document.getElementById('textfield').value=this.value" />
                        @*<input type="submit" name="submit" class="btn" value="上传" />*@

                    </div>

                </div>
                <br />
                <div class="editor-field">
                    <button class="btn btn-lg btn-primary">确定</button>
                </div>
            </div>


        }

    </div>

</div>



<style type="text/css">
    .file-box {
        position: relative;
        width: 340px;
    }

    .txt {
        height: 30px;
        border: 1px solid #cdcdcd;
        width: 180px;
    }



    .file {
        position: absolute;
        top: 0;
        right: 80px;
        height: 24px;
        filter: alpha(opacity:0);
        opacity: 0;
        width: 260px;
    }
</style>

<script src="~/Content/js/jquery-1.10.2.min.js"></script>
<script src="~/Content/js/bootstrap.min.js"></script>
<script src="~/Content/js/bootstrap-datetimepicker.js"></script>
<script src="~/Content/js/bootstrap-datetimepicker.zh-CN.js"></script>

<script type="text/javascript">
    $('.form_datetime').datetimepicker({
        //language:  'fr',
        weekStart: 1,
        todayBtn: 1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 2,
        forceParse: 0,
        showMeridian: 1
    });
    $('.form_date').datetimepicker({
        language: 'fr',
        weekStart: 1,
        todayBtn: 1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 2,
        minView: 2,
        forceParse: 0
    });
    $('.form_time').datetimepicker({
        language: 'fr',
        weekStart: 1,
        todayBtn: 1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 1,
        minView: 0,
        maxView: 1,
        forceParse: 0
    });
</script>

MVCAPP/Views/PartyActivities/MyPartyInformation.cshtml
@{
    Layout = null;
}
@model ViewModel.PartyInformationModel

<link rel="stylesheet" href="../../Content/button/css/font-awesome.min.css">
<link rel="stylesheet" href="../../Content/button/css/buttons.css">

<div  style="background-color:#fff;">
    <div style="background-color:#fff;display:block;position:relative; ">
        &nbsp;&nbsp;&nbsp;
       @if (Model.partyInfo.partyLogo != null)
       {
           <img src="@Model.partyInfo.partyLogo" style="width:150px;height:150px;" class="img-circle" />
       }
       else
       {
            <img src="~/Content/Images/default.jpg" style="width:150px;height:150px;" class="img-circle" />
       }
        
        <div id="party-info" style="display:block; position:absolute;left:200px;top:10px;">
            <fieldset>

                <div class="editor-label">
                    <label>社团名称：</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.DisplayFor(m => m.partyInfo.partyName)
                </div>



                <div class="editor-label">
                    <label>社团宗旨：</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.DisplayFor(m => m.partyInfo.partyPurpose)
                </div>



                <div class="editor-label">
                    <label>社团性质：</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.DisplayFor(m => m.partyInfo.partyProperty)
                </div>
                <div class="editor-label">
                    <label>社团使命：</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.DisplayFor(m => m.partyInfo.partyTask)
                </div>

               
                <div class="editor-label">
                    <label>建立时间:</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.DisplayFor(m => m.partyInfo.partyFoundingTime)

                </div>
                
            </fieldset>

        </div>

        @*添加活动div*@
        <div style="display:block;position:absolute;right:20px;top:10px;">

            <a class="button button-circle button-primary" onclick="window.location = '/PartyActivities/AddActivities'" role="button">添加活动</a>

        </div>
      
    </div>


  
   
</div>

MVCAPP/Views/PartyActivities/SetPartyInfo.cshtml
@{
    ViewBag.Title = "SetPartyInfo";
}

@model  ViewModel.PartyInfo


<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Tomato</a>
        </div>
        <!--[logo]>
        <a class="navbar-brand" href="#">
        </a> <!-->
        <ul class="nav navbar-nav " role="tablist">
            <li><a href="/Home/Index">首页</a></li>
            <li><a href="/PartyActivities/PartyIndex">社团互动</a></li>
            <li><a href="/MarketDownstairs/MarketIndex">楼下小铺</a></li>
            <li><a href="#">新生指南</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            @if (User.IsInRole("社团"))
            {
                // [@Html.ActionLink("个人中心", "PersonalInfo", "Account")]
                //[ @Html.ActionLink("注销", "LogOff", "Account") ]
                <li style="color:white">
                    <a>欢迎<small>@User.Identity.Name !</small></a>
                </li>
                <li class="active"><a href="/PartyActivities/SetPartyInfo?partyName=@User.Identity.Name">社团中心</a></li>
                <li><a href="/Account/LogOff">注销</a></li>



            }
            @if (!User.IsInRole("社团"))
            {

                <li><a href="/Account/PartyLoginIndex">登陆/注册</a></li>

            }
        </ul>
    </div>
</nav>


<div class="container" style="background-color:#fff;height:900px;">


    <div style="display:block;position:relative;top:54px;">

        @Html.Action("MyPartyInformation", new { partyName = @ViewBag.partyName })
        @*导航菜单*@
        <ul class="nav nav-tabs" contenteditable="true" style="background-color:#eee7e7">
            <li id="mygoodli" class="active"><a onclick="window.location = '/PartyActivities/SetPartyInfo?partyName=@ViewBag.partyName'" role="button">基本信息设置</a></li>

            <li id="myactivities"><a onclick="window.location = '/PartyActivities/MyPartyActivities?partyName=@ViewBag.partyName'" role="button">社团活动</a></li>

            <li id="mynoticeli"><a onclick="window.location = '/PartyActivities/Notice?partyName=@ViewBag.partyName'" role="button">通知</a></li>

            <li id="myupdatepassword"><a onclick="window.location = '/PartyActivities/UpdatePassword?partyName=@ViewBag.partyName'" role="button">修改密码</a></li>
        </ul>

        <div aria-multiline="True" style=" background-color:#fff ;overflow:scroll;height:auto;">
            @using (Html.BeginForm("SetPartyInfo", "PartyActivities", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
            {

            <div id="party-infoform" style="display:block; position:relative;top:10px;">
            <fieldset>

                <div class="editor-label">
                    <label>社团名称：</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.TextBoxFor(m => m.partyName, new { @class = "form-control", placeholder = "社团名称", style = "disabled" })
                </div>



                <div class="editor-label">
                    <label>社团宗旨：</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.TextBoxFor(m => m.partyPurpose, new { @class = "form-control", placeholder = "社团宗旨" })
                </div>



                <div class="editor-label">
                    <label>社团性质：</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.TextBoxFor(m => m.partyProperty, new { @class = "form-control", placeholder = "社团性质" })
                </div>
                <div class="editor-label">
                    <label>社团使命：</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.TextBoxFor(m => m.partyTask, new { @class = "form-control", placeholder = "社团使命" })
                </div>
                <div class="editor-label">
                    <label>社团活动：</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.TextBoxFor(m => m.partyActivities, new { @class = "form-control", placeholder = "社团活动" })
                </div>

                <div class="editor-label">
                    <label>社团成员:</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.TextBoxFor(m => m.partyMembers, new { @class = "form-control", placeholder = "社团成员" })
                </div>
                <div class="editor-label">
                    <label>建立时间:</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.TextBoxFor(m => m.partyFoundingTime, new { @class = "form-control", placeholder = "建立时间" })

                </div>
                <div class="editor-label">
                    <label>社团简介:</label>
                    &nbsp;&nbsp;&nbsp;
                    @Html.TextAreaFor(m => m.partyDescribe, new { @class = "form-control", placeholder = "社团简介" })

                </div>
                <div>
                    <label>
                        上传logo：
                    </label>
                    <div class="file-box">
                        <input type='text' name='textfield' id='textfield' class='txt' />
                        <input type='button' class='btn' value='浏览...' />
                        <input type="file" name="image" class="file" id="fileField" size="28" onchange="document.getElementById('textfield').value=this.value" />
                        @*<input type="submit" name="submit" class="btn" value="上传" />*@

                    </div>

                </div>

                <br />
                <div class="editor-label">
                    <button type="submit" class="btn btn-primary">更改信息</button>
                </div>
            </fieldset>
        </div>

            }


        </div>
    </div>
</div>

<style type="text/css">
    .file-box {
        position: relative;
        width: 340px;
    }

    .txt {
        height: 30px;
        border: 1px solid #cdcdcd;
        width: 180px;
    }



    .file {
        position: absolute;
        top: 0;
        right: 80px;
        height: 24px;
        filter: alpha(opacity:0);
        opacity: 0;
        width: 260px;
    }
</style>

MVCAPP/Views/PartyActivities/UpdatePassword.cshtml
@{
    ViewBag.Title = "UpdatePassword";
}

@model ViewModel.partyUpdatePasswordModel

<!--导航栏-->
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Tomato</a>
        </div>
        <!--[logo]>
        <a class="navbar-brand" href="#">
        </a> <!-->
        <ul class="nav navbar-nav " role="tablist">
            <li><a href="/Home/Index">首页</a></li>
            <li><a href="/PartyActivities/PartyIndex">社团互动</a></li>
            <li><a href="/MarketDownstairs/MarketIndex">楼下小铺</a></li>
            <li><a href="#">新生指南</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            @if (User.IsInRole("社团"))
            {
                // [@Html.ActionLink("个人中心", "PersonalInfo", "Account")]
                //[ @Html.ActionLink("注销", "LogOff", "Account") ]
                <li style="color:white">
                    <a>欢迎<small>@User.Identity.Name !</small></a>
                </li>
                <li class="active"><a href="/PartyActivities/SetPartyInfo?partyName=@User.Identity.Name">社团中心</a></li>
                <li><a href="/Account/LogOff">注销</a></li>



            }
            @if (!User.IsInRole("社团"))
            {

                <li><a href="/Account/PartyLoginIndex">登陆/注册</a></li>

            }
        </ul>
    </div>
</nav>


<div class="container" style="background-color:#fff;height:800px;">

    <div style="display:block;position:relative;top:54px;">



        @Html.Action("MyPartyInformation", new { partyName = @User.Identity.Name })

        @*导航菜单*@
        <ul class="nav nav-tabs" contenteditable="true" style="background-color:#eee7e7">
            <li id="mygoodli"><a onclick="window.location = '/PartyActivities/SetPartyInfo?partyName=@User.Identity.Name'" role="button">基本信息设置</a></li>

            <li id="myactivities"><a onclick="window.location = '/PartyActivities/MyPartyActivities?partyName=@User.Identity.Name'" role="button">社团活动</a></li>

            <li id="mynoticeli"><a onclick="window.location = '/PartyActivities/Notice?partyName=@User.Identity.Name'" role="button">通知</a></li>

            <li id="myupdatepassword" class="active"><a onclick="window.location = '/PartyActivities/UpdatePassword?partyName=@ViewBag.partyName'" role="button">修改密码</a></li>

        </ul>

        <div aria-multiline="True" style=" background-color:#fff ;overflow:scroll;height:auto;">
            @using (Html.BeginForm("UpdatePassword", "PartyActivities", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
            {

                <div id="party-infoform" style="display:block; position:relative;top:10px;">
                    <fieldset>

                        <div class="editor-label">
                            <label>旧密码：</label>
                            &nbsp;&nbsp;&nbsp;
                            @Html.TextBoxFor(m => m.oldPassword, new { @class = "form-control", type = "password", placeholder = "旧密码" })
                            @Html.ValidationMessageFor(m => Model.oldPassword)
                        </div>

                        <div class="editor-label">
                            <label>新密码：</label>
                            &nbsp;&nbsp;&nbsp;
                            @Html.TextBoxFor(m => m.newPassword, new { @class = "form-control", type = "password", placeholder = "新密码" })
                            @Html.ValidationMessageFor(m => Model.newPassword)
                        </div>

                        <div class="editor-label">
                            <label>新密码确认：</label>
                            &nbsp;&nbsp;&nbsp;
                            @Html.TextBoxFor(m => m.newPasswordAgain, new { @class = "form-control", type = "password", placeholder = "新密码确认" })
                            @Html.ValidationMessageFor(m => Model.newPasswordAgain)
                        </div>
                        <div class="editor-label">
                            <label>验证码：</label>
                            &nbsp;&nbsp;&nbsp;
                            @Html.TextBoxFor(m => m..confirmCode, new { @class = "form-control", type = "text", placeholder = "验证码" })
                            <br />
                            <img src='/Common/GetImage' />
                            @Html.ValidationMessageFor(m => Model.confirmCode)
                        </div>

                                       
                        <br />
                        <div class="editor-label">
                            <button type="submit" class="btn btn-primary">修改密码</button>
                        </div>
                    </fieldset>
                </div>

            }


        </div>
    </div>

</div>